### PR TITLE
Test/travis

### PR DESCRIPTION
**Pull request by thisiscab**

### CODE REVIEW

**Comment by braidn** [comment]
Are there plans to reword that 'MAYBE' commit?

**Comment by thisiscab** [comment]
The goal is to destroy that PR after I can ensure that my tests are passing on Travis. I didn't want to polute the other branches

**Comment by braidn** [comment]
Absolutely! If you want though you can totally rebase out a commit and force push. Whatever seems easier for yah.

**Comment by thisiscab** [comment]
This served only for Travis testing, this PR is not relevant anymore.

**Pull request closed without merging**
