### PR TITLE
Fix/adding bundled items

### PR DESCRIPTION
**Pull request by papayaah**
@bryanmtl @cabouffard 

this changes applies adjustments to bundled item's parts.

### CODE REVIEW

**Comment by thisiscab** [comment]
I think we have to manually set-up some stuff in our Rubcop file since the latest version of it doesn't use the same default has previously.

**Comment by papayaah** [comment]
not exactly sure now how to get rid of the warning.

**Comment by papayaah** [comment]
made another tweak on the rubocop setting, should be green now.

**Comment by bryanmtl** [comment]
Thanks guys.

**Pull request merged**
