### PR TITLE
add a text field in the admin to filter by pos order number

### PR DESCRIPTION
**Pull request by papayaah**
@bryanmtl 

image

### CODE REVIEW

**Comment by bryanmtl** [comment]
@mickeyren Can you add a test for this?

**Comment by papayaah** [comment]
sure Bryan, i'll put in a feature test like Solidus - https://github.com/solidusio/solidus/blob/master/backend/spec/features/admin/orders/listing_spec.rb

**Comment by bryanmtl** [comment]
Thanks!

**Comment by papayaah** [comment]
@bryanmtl spec is in :)

**Comment by bryanmtl** [comment]
@mickeyren Thanks!

**Pull request merged**
