### PR TITLE
Add Ignored Files Generated From Boxen

### PR DESCRIPTION
**Pull request by braidn**
Gitignore update

### CODE REVIEW

**Comment by braidn** [comment]
Just a few tweaks to the gitignore for boxen related files.

**Comment by thisiscab** [comment]
Good catch! Totally forgot about Boxen :)

**Comment by braidn** [comment]
Yeah not going to call out for a CR but will keep open for a bit to allow anyone to air grievances

**Comment by DanielWright** [comment]
The only "grievance" I can think of is the absence of motivation for a Node runtime or PhantomJS environment (or dotenv, for that matter). But updating the gitignore seems too fine a hair to split on these matters.

**Comment by braidn** [comment]
PRECISELY! And with this there is a permanent blocker unless you add them in yourself.

**Comment by DanielWright** [comment]
Didn't think about it that way. Genius! 🎉

**Pull request merged**
