### PR TITLE
Travis, meet VCR; VCR, Travis. 👬

### LINKED ISSUE #27: VCR not behaving correctly on Travis
I'm having big trouble with VCR at the moment, where the behavior is different on Travis compared to locally. 

Locally everything is green and I see that it uses the cassette correctly. When I look at the request URL of my cassettes, it requests at the proper URL which is:
`https://1b7f63bf248831c7ae2beacf9bc30bbb:b1c915515d08e2037930a844f7436610@glossier-pop-staging.myshopify.com/x/y.json`

When pushing to Travis, it makes requests to `https://glossier-pop-staging.myshopify.com/x/y`, which makes the requests fails due to VCR raising this error: `VCR::Errors::UnhandledHTTPRequestError`.

The way I setup the ShopifyURL is the following:
https://github.com/glossier/solidus_retail/blob/69e5e6c906ed64f3a631a477c805ccd5d6e1bf33/config/initializers/shopify.rb

Here is how I'm saving the cassettes: 

``` ruby
      if example.metadata[:type] == :request
        name = example.metadata[:full_description].split(/\s+/, 2).join('/').underscore.tr('.', '/').gsub(/[^\w\/]+/, '_').gsub(/\/$/, '')
        VCR.use_cassette(name, {}, &example)
      else
        VCR.turned_off(&example)
      end
```

The ENVS variables are correctly set.

DW indirectly suggested that we mock the requests based on the domain name instead of the full URL by doing the following: https://github.com/glossier/solidus_retail/blob/321aac51dc215ad1a77e15f68e72adb62c281380/spec/support/vcr.rb

The problem with this implementation is that it seems to always return the same value when the same requests is being called multiple times in-within the same block. So if I fetch the number of Posts from the API at the beginning of my spec and later on down the road I refetch the number of posts, since the requests already exists it will return me the result of the first call, which is bonker and not what I want, since this makes my whole spec suite go red.

Any suggestions? :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by DanielWright**
Travis and VCR currently don't get along, but they were meant to be together. This PR proposes to mend their respective fences, and get them back into a productive relationship.

Merging this PR will (hopefully!) resolve #27.

### CODE REVIEW

**Comment by DanielWright** [comment]
@cabouffard Want to take a look?

**Comment by thisiscab** [comment]
That looks legit, so we are not using the cassette if we're on Travis? I thought the goal was to use the cassettes no matter what ENV we were on, in order to make the process faster!

**Comment by DanielWright** [comment]
No, we will use cassettes in either case, but Travis won't _record_ cassettes.

**Comment by thisiscab** [comment]
Ahhh got it, I read that wrong. Okay. Let's see how it works out on the `simple-product-export` branch, what do you think?

**Comment by DanielWright** [comment]
Sounds good to me! You have to add the `:vcr` metadata to the examples you want VCR to track, that's it.

**Pull request merged**
